- name: Configuration initiale de la VM
  hosts: servers
  become: yes
  vars_files:
    - vault.yaml

  tasks:
    - name: Configurer timezone
      timezone:
        name: Europe/Paris

    - name: Mettre à jour le système
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installer outils essentiels
      apt:
        name:
          - curl
          - wget
          - git
          - net-tools
          - htop
        state: present

    - name: Créer un utilisateur spécifique
      user:
        name: "{{ new_user }}"
        state: present
        groups: sudo
        create_home: yes

    - name: Ajouter une clé SSH pour le nouvel utilisateur
      authorized_key:
        user: "{{ new_user }}"
        key: "{{ lookup('file', 'id_rsa.pub') }}"